name: bongga_flutter_map
description: A new Flutter package to display a custom flutter_map
version: 0.0.5
author: Bongga
homepage: https://bongga.co

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: 
    git:
      url: https://github.com/bongga-co/flutter_map.git

  rxdart: 0.22.2
  geolocator: 5.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
